
// TYPES FOR USER
export const GET_USER = "GET_USER"
export const USE_USER = "USE_USER"
export const GET_USER_IMAGE = "GET_USER_IMAGE"

// TYPES FOR CONTACTS
export const GET_CONTACTS = "GET_CONTACTS"
export const DELETE_CONTACT = "DELETE_CONTACT"
export const GET_CONTACTS_PHONE_NUMBERS = "GET_CONTACTS_PHONE_NUMBERS" 
export const DELETE_CONTACTS_PHONE_NUMBERS = "DELETE_CONTACTS_PHONE_NUMBERS" 
export const GET_CONTACT_ID = "GET_CONTACT_ID" 

